db:
  host: xxx
  userName: xx
  password: xxx
  port: xx
  dataBase: brewery
doubao:
  apiKey: xxx
  modelId: xxx
redis:
  address: xxx
  password: xx
  db: xx
ethereum:
  addr:
    ws: ws://127.0.0.1:8545
    http: http://127.0.0.1:8545/
contracts:
  address:
    guideNFT: 0x5FbDB2315678afecb367f032d93F642f64180aa3