db:
  host: xxxx
  userName: xxxx
  password: xxxx@
  port: xxxx
  dataBase: xxxx
doubao:
  apiKey: xxxx
  modelId: xxxx
redis:
  address: xxxx
  password: xxxx
  db: xxxx
contracts:
  address:
    guideNFT: xxxx
